# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

#Pipelines > Stages > Jobs > Tasks(Steps)
jobs:
  - job:Job02
    steps:
    - script: echo Job02
  - job:Job03
    steps:
    - script: echo Job02    
